name: kconnect_mobile
description: "K-Connect - Social platform"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.3.1
  cookie_jar: ^4.0.8
  cupertino_back_gesture: ^0.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  http: ^1.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_svg: ^2.2.2
  liquid_glass_renderer: ^0.2.0-dev.4
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.6

  shared_preferences: ^2.2.3
  intl: ^0.20.2
  shimmer: ^3.0.0
  wolt_modal_sheet: ^0.11.0
  dartz: ^0.10.1
  path_provider: ^2.1.5
  flutter_cache_manager: ^3.3.1
  just_audio: ^0.10.5
  audio_service: ^0.18.12
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  video_player: ^2.8.1
  chewie: ^1.8.1
  photo_view: ^0.15.0
  uuid: ^4.4.0
  web_socket_channel: ^2.4.0
  wechat_assets_picker: ^9.1.0
  photo_manager: ^3.6.3
  photo_manager_image_provider: ^2.2.0
  url_launcher: ^6.3.1
  rxdart: ^0.28.0
  palette_generator: ^0.3.3+7
  progress_indicator_m3e: ^0.1.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/icons/social_icons/
    - lib/assets/icons/status_icons/
    - lib/assets/images/
    - lib/assets/audio/

fonts:
  - family: Mplus
    fonts:
      - asset: lib/assets/fonts/Mplus/MPLUS1-Black.ttf
        weight: 900
      - asset: lib/assets/fonts/Mplus/MPLUS1-Bold.ttf
        weight: 700
      - asset: lib/assets/fonts/Mplus/MPLUS1-ExtraBold.ttf
        weight: 800
      - asset: lib/assets/fonts/Mplus/MPLUS1-ExtraLight.ttf
        weight: 200
      - asset: lib/assets/fonts/Mplus/MPLUS1-Light.ttf
        weight: 300
      - asset: lib/assets/fonts/Mplus/MPLUS1-Medium.ttf
        weight: 500
      - asset: lib/assets/fonts/Mplus/MPLUS1-Regular.ttf
        weight: 400
      - asset: lib/assets/fonts/Mplus/MPLUS1-SemiBold.ttf
        weight: 600
      - asset: lib/assets/fonts/Mplus/MPLUS1-Thin.ttf
        weight: 100
  - family: Poppins
    fonts:
      - asset: lib/assets/fonts/Poppins/Poppins-Black.ttf
        weight: 900
      - asset: lib/assets/fonts/Poppins/Poppins-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: lib/assets/fonts/Poppins/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: lib/assets/fonts/Poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: lib/assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: lib/assets/fonts/Poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: lib/assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: lib/assets/fonts/Poppins/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: lib/assets/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: lib/assets/fonts/Poppins/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: lib/assets/fonts/Poppins/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: lib/assets/fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: lib/assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: lib/assets/fonts/Poppins/Poppins-Thin.ttf
        weight: 100
      - asset: lib/assets/fonts/Poppins/Poppins-ThinItalic.ttf
        weight: 100
        style: italic

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/assets/icons/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/assets/icons/icon.png"
  web:
    generate: true
    image_path: "lib/assets/icons/icon.png"
